### ISSUE TITLE
Tutorial FMU behaviour

### ISSUE THREAD

**Issue by KristofferSkare** [open-simulation-platform/demo-cases#55]
There seems to be some behavior of the tutorial FMUs (mass-spring-damper system) that is not according to how the corresponding physical system would behave. It is very noticeable for some parameter settings, but I think it also slightly influences many other simulations where it is not as noticeable. This happens both when I download the FMUs on this repo and using the ones that are on STC.  I think this is because the implementation of the damper is wrong. 

This happens when the damperCoefficient is set high and the springStiffness is set to a low value. This makes it so the dominating force in the system is the damping force. In the physical system this would just make the mass slowly move toward the steady state position.

The figure below is what is simulated by STC with the parameters listed at the bottom. The green function is the x position of the mass. In this simulation the mass moves 6 kilometers in under 15 seconds! This must be unrealistic with the parameters described at the bottom.

As mentioned I think this is because the damper is implemented wrong. In the plot the x velocity of the mass is in blue and the damper force in the x direction is in orange. In the beginning of the simulation the damper force is in the same direction as the velocity (both positive). This cases the velocity to increase with again increases the damper force and causes a positive feedback loop. This causes the mass to accelerate incredibly fast in the positive x direction. This positive feedback loop is only stopped when the mass is far enough from the starting position that the spring force is stronger than the damper force causing the x velocity to decrease. 

The problem with the damper force calculation is that it makes it possible for the damper force to be in the same direction as the velocity.

I have an idea of what might be wrong with the implementation, but I do not know exactly what the correct implementation would be.

![image](https://github.com/open-simulation-platform/demo-cases/assets/52509111/f9082aa3-e5de-4833-a223-ad5903ecee5b)

Parameters used in simulation:
 * springStiffness: 1
 * damperCoefficient: 10
 * initialPositionX: -10
 * initialPositionY: -10
 * initialVelocity: 10
 * initialVelocity: 10
 * The rest are just the default values (I don't think they matter much for showing the problem)

**Comment by SSkjong** [comment]
Have you tried to vary the local time step size (`timeStep`), or changing the solver type (`solverType`)? It could be that you enter a stability issue with the current configuration. I have not looked at the details, but see below for the implementations:

Spring:
```cpp
#include "modelName.h"
#include SYSTEM_HEADER
#include "guid.h"

#include "livePlot.h"
#include "plotFunctions.h"
#include <fstream>
#include <iostream>

#define _USE_MATH_DEFINES
#include <cmath>

/*! \file system.cpp
 * \brief This file holds the implementation of the fmu's dynamics. The relevant
 * theory is documented \ref Theory "here". For more information regarding how
 * to make a new fmu, see \ref createFMU. The specific implementation
 * documentation can be found in \ref system.cpp.
 */

/*! \brief This function is called by the System constructor and sets up the
 * system System class, which holds the state-space model, the dynamics and the
 * characteristics of the FMU. Note that the System class inherits from the
 * SystemBase class.
 */
MODEL_IDENTIFIER::MODEL_IDENTIFIER(std::shared_ptr<LoggerBase> _logger)
    : SystemBaseWithSolvers(_logger)
{
    author      = "Stian Skjong";
    description = "A simple linear spring";
    version     = MODEL_VERSION;
    name        = MODELNAME;
    identifier  = MODEL_IDENTIFIER_STR;
    guid        = fmuGUID;

    /*PARAMETERS*/
    RegisterReal(k, "springStiffness", 5.0);
    RegisterReal(initialLength, "zeroForceLength", 0.0);

    /*SIMULATION SPECIFIC PARAMETERS*/
    solverType = "None";   // Integration method
                           // (RKF45, RK4, RK2, VRK2, Euler, None)
    timeStep     = 0.001;  // NB! Local solver time step
    relTolerance = 1.0e-4; // local tolerance if variable step size solver is
                           // used (VRK2 or RKF45).
    absTolerance = 1.0e-4; // local tolerance if variable step size solver is
                           // used (VRK2 or RKF45).

    /*PLOTTING SETTINGS*/
    plotLength   = 1000; // Max length of plotting vectors
    livePlotting = 1;    // Plot states (y/n)
    plotDt       = 0.1;  // How often to update plot

    /*INPUTS AND OUTPUTS*/
    // Note that the I/O names here are poorly chosen, on purpose,
    // for demonstration purposes.
    RegisterInput(xXA, "dis_xx", 0.0);
    RegisterInput(xYA, "dis_yx", 0.0);
    RegisterOutput(forceXA, "for_xx", 0.0);
    RegisterOutput(forceYA, "for_yx", 0.0);

    data = std::vector<std::vector<double>>(2 + 1);
}

void MODEL_IDENTIFIER::InitialCalc()
{
    xXB = 0.0;
    xYB = 0.0;

    // calculating angle
    double length          = sqrt(pow(xXA - xXB, 2.0) + pow(xYA - xYB, 2.0));
    double effectiveLength = length - initialLength;

    if (length > 0.0)
    {
        forceXA = -k * effectiveLength * (xXA - xXB) / length;
        forceYA = -k * effectiveLength * (xYA - xYB) / length;
    }
    else
    {
        forceXA = 0.0;
        forceYA = 0.0;
    }
    forceXB = -forceXA;
    forceYB = -forceYA;
}

void MODEL_IDENTIFIER::SolverPreCalc() { }

void MODEL_IDENTIFIER::OdeFunctionCalc() { }

/// Function called after the solver.
void MODEL_IDENTIFIER::SolverPostCalc()
{
    // calculating angle
    double length          = sqrt(pow(xXA - xXB, 2.0) + pow(xYA - xYB, 2.0));
    double effectiveLength = length - initialLength;

    if (length > 0.0)
    {
        forceXA = -k * effectiveLength * (xXA - xXB) / length;
        forceYA = -k * effectiveLength * (xYA - xYB) / length;
    }
    else
    {
        forceXA = 0.0;
        forceYA = 0.0;
    }
    forceXB = -forceXA;
    forceYB = -forceYA;

    data[0].emplace_back(time);
    data[1].emplace_back(forceXA);
    data[2].emplace_back(forceYA);

    if (livePlotting)
    {
        PlottingInSubPlots(*this);
    }
}

/// Function called right before termination of the fmu.
void MODEL_IDENTIFIER::FinalCalc()
{

    if (livePlotting)
    {
        Plotting_End();
    }
}
```
Mass:
```cpp
#include "modelName.h"
#include SYSTEM_HEADER
#include "guid.h"

#include "livePlot.h"
#include "plotFunctions.h"
#include <fstream>
#include <iostream>

#define _USE_MATH_DEFINES
#include <cmath>

/*! \file system.cpp
 * \brief This file holds the implementation of the fmu's dynamics. The relevant theory is documented \ref Theory "here". For more information regarding how to make a new fmu, see \ref createFMU. The specific implementation documentation can be found in \ref system.cpp.
 */

/*! \brief This function is called by the System constructor and sets up the system System class, which holds the state-space model, the dynamics and the characteristics of the FMU. Note that the System class inherits from the SystemBase class.
  */
MODEL_IDENTIFIER::MODEL_IDENTIFIER(std::shared_ptr<LoggerBase> _logger)
    : SystemBaseWithSolvers(_logger)
{
    author      = "Stian Skjong";
    description = "A simple mass model, which can be affected by gravity";
    version     = MODEL_VERSION;
    name        = MODELNAME;
    identifier  = MODEL_IDENTIFIER_STR;
    guid        = fmuGUID;

    /*PARAMETERS*/
    RegisterReal(m, "mass", 10.0);
    RegisterReal(Cd, "dragCoefficient", 0.47); // Spherical shape, Rn ~ 10^4
    RegisterReal(diam, "diameter", 0.2);
    RegisterReal(rho, "mediumDensity", 1.0); // Air assumed
    RegisterReal(g, "gravity", -9.81);
    RegisterReal(posX0, "initialPositionX", 0.0);
    RegisterReal(velX0, "initialVelocityX", 0.0);
    RegisterReal(posY0, "initialPositionY", 0.0);
    RegisterReal(velY0, "initialVelocityY", 0.0);
    RegisterBoolean(inGravityField, "inGravityField", true);
    RegisterBoolean(enableDrag, "enableDrag", true);

    /*SIMULATION SPECIFIC PARAMETERS*/
    solverType   = "Euler"; //Integration method (RKF45, RK4, RK2, VRK2, Euler, None)
    timeStep     = 0.001;   //NB! Local solver time step
    relTolerance = 1.0e-4;  //local tolerance if variable step size solver is used.
    absTolerance = 1.0e-4;  //local tolerance if variable step size solver is used.

    /*PLOTTING SETTINGS*/
    plotLength   = 1000; // Max length of plotting vectors
    livePlotting = 1;    // Plot states (y/n)
    plotDt       = 0.1;  // How often to update plot

    RegisterState(posX, velX, "positionX", posX0, StateVisibility::Internal);
    RegisterState(posY, velY, "positionY", velX0, StateVisibility::Internal);
    RegisterState(velX, accX, "velocityX", posY0, StateVisibility::Internal);
    RegisterState(velY, accY, "velocityY", velY0, StateVisibility::Internal);

    /*INPUTS AND OUTPUTS*/
    // Note that the I/O names here are poorly chosen, on purpose,
    // for demonstration purposes.
    RegisterInput(damperForceX, "in_f_u", 0.0);
    RegisterInput(damperForceY, "in_f_w", 0.0);
    RegisterInput(springForceX, "in_l_u", 0.0);
    RegisterInput(springForceY, "in_l_w", 0.0);
    RegisterOutput(posX, "out_l_u", 0.0);
    RegisterOutput(posY, "out_l_w", 0.0);
    RegisterOutput(velX, "out_f_u", 0.0);
    RegisterOutput(velY, "out_f_w", 0.0);

    data = std::vector<std::vector<double>>(xTot.size() + 1);
}

void MODEL_IDENTIFIER::InitialCalc()
{
    posX = posX0;
    velX = velX0;
    posY = posY0;
    velY = velY0;
}

void MODEL_IDENTIFIER::SolverPreCalc() { }

void MODEL_IDENTIFIER::OdeFunctionCalc()
{
    accX = 1.0 / m * (springForceX + damperForceX);
    accY = 1.0 / m * (springForceY + damperForceY);
    if (inGravityField)
        accY += g;
    if (enableDrag)
    {
        accX -= 1.0 / m * (0.5 * diam * diam * 0.25 * pi * Cd * rho * velX * std::fabs(velX));
        accY -= 1.0 / m * (0.5 * diam * diam * 0.25 * pi * Cd * rho * velY * std::fabs(velY));
    }
}

/// Function called after the solver.
void MODEL_IDENTIFIER::SolverPostCalc()
{
    if (livePlotting)
    {
        PlottingStates(*this);
    }
}

/// Function called right before termination of the fmu.
void MODEL_IDENTIFIER::FinalCalc()
{

    if (livePlotting)
    {
        Plotting_End();
    }
}
```
Damper:
```cpp
#include "modelName.h"
#include SYSTEM_HEADER
#include "guid.h"

#include "livePlot.h"
#include "plotFunctions.h"
#include <fstream>
#include <iostream>

#define _USE_MATH_DEFINES
#include <cmath>

/*! \file system.cpp
 * \brief This file holds the implementation of the fmu's dynamics. The relevant
 * theory is documented \ref Theory "here". For more information regarding how
 * to make a new fmu, see \ref createFMU. The specific implementation
 * documentation can be found in \ref system.cpp.
 */

/*! \brief This function is called by the System constructor and sets up the
 * system System class, which holds the state-space model, the dynamics and the
 * characteristics of the FMU. Note that the System class inherits from the
 * SystemBase class.
 */
MODEL_IDENTIFIER::MODEL_IDENTIFIER(std::shared_ptr<LoggerBase> _logger)
    : SystemBaseWithSolvers(_logger)
{
    author      = "Stian Skjong";
    description = "A simple mechanical, linear damper";
    version     = MODEL_VERSION;
    name        = MODELNAME;
    identifier  = MODEL_IDENTIFIER_STR;
    guid        = fmuGUID;

    /*PARAMETERS*/
    RegisterReal(b, "dampingCoefficient", 2.0);

    /*SIMULATION SPECIFIC PARAMETERS*/
    solverType = "Euler";  // Integration method
                           // (RKF45, RK4, RK2, VRK2, Euler, None)
    timeStep     = 0.001;  // NB! Local solver time step
    relTolerance = 1.0e-4; // local tolerance if variable step size solver is
                           // used (VRK2 or RKF45).
    absTolerance = 1.0e-4; // local tolerance if variable step size solver is
                           // used (VRK2 or RKF45).

    /*PLOTTING SETTINGS*/
    plotLength   = 1000; // Max length of plotting vectors
    livePlotting = 1;    // Plot states (y/n)
    plotDt       = 0.1;  // How often to update plot

    /*STATES*/
    RegisterState(xXA, vXA, "posXA", 0.0, StateVisibility::Internal);
    RegisterState(xXB, vXB, "posXB", 0.0, StateVisibility::Internal);
    RegisterState(xYA, vYA, "posYA", 0.0, StateVisibility::Internal);
    RegisterState(xYB, vYB, "posYB", 0.0, StateVisibility::Internal);

    /*INPUTS AND OUTPUTS*/
    // Note that the I/O names here are poorly chosen, on purpose,
    // for demonstration purposes.
    RegisterInput(vXA, "lv_0", 0.0);
    RegisterInput(vYA, "lv_1", 0.0);
    RegisterOutput(forceXA, "df_0", 0.0);
    RegisterOutput(forceYA, "df_1", 0.0);

    data = std::vector<std::vector<double>>(2 + 1);
}

void MODEL_IDENTIFIER::InitialCalc()
{
    vXB = 0.0;
    vYB = 0.0;

    double length = sqrt(pow(xXA - xXB, 2.0) + pow(xYA - xYB, 2.0));
    if (length > 0.0)
    {
        forceXA = b * (vXA - vXB) * (xXA - xXB) / length;
        forceYA = b * (vYA - vYB) * (xYA - xYB) / length;
    }
    else
    {
        forceXA = 0.0;
        forceYA = 0.0;
    }
}

void MODEL_IDENTIFIER::SolverPreCalc() { }

void MODEL_IDENTIFIER::OdeFunctionCalc() { }

/// Function called after the solver.
void MODEL_IDENTIFIER::SolverPostCalc()
{
    double length = sqrt(pow(xXA - xXB, 2.0) + pow(xYA - xYB, 2.0));
    if (length > 0.0)
    {
        forceXA = b * (vXA - vXB) * (xXA - xXB) / length;
        forceYA = b * (vYA - vYB) * (xYA - xYB) / length;
    }
    else
    {
        forceXA = 0.0;
        forceYA = 0.0;
    }

    forceXB = -forceXA;
    forceYB = -forceYA;

    data[0].emplace_back(time);
    data[1].emplace_back(forceXA);
    data[2].emplace_back(forceYA);

    if (livePlotting)
    {
        PlottingInSubPlots(*this);
    }
}

/// Function called right before termination of the fmu.
void MODEL_IDENTIFIER::FinalCalc()
{

    if (livePlotting)
    {
        Plotting_End();
    }
}
```

**Comment by SSkjong** [comment]
The theory of the models are given as follows:
Spring:
![image](https://github.com/open-simulation-platform/demo-cases/assets/48753541/d1b99f0d-4580-47e4-8168-941e8d675ab1)
Mass:
![image](https://github.com/open-simulation-platform/demo-cases/assets/48753541/76be39a6-4dc7-4fe4-b3e1-ff193311c42f)
Damper:
![image](https://github.com/open-simulation-platform/demo-cases/assets/48753541/7eb56c03-61de-4551-be9d-d958a6196fcf)

**Comment by KristofferSkare** [comment]
Hi

Thanks for the response. 

I looked into the implementation in the FMUs by opening them up before posting the issue. Looking at the code I could see where the bug is. Looking at the theory you posted I see that it agrees with the code in the damper FMU. However, I think that it is the actual theory of the damper that is wrong. 

Long story short I think the correct equation is:

$$
 \Delta p = \begin{bmatrix} x_{A} - x_{B} \\\ y_{A} - y_{B} \end{bmatrix}
$$

$$
 \Delta v = \begin{bmatrix} v_{Ax} - v_{Bx} \\\ v_{Ay} - v_{By} \end{bmatrix}
$$

$$
L = \sqrt{(x_A - x_B)^2 + (y_A - y_B)^2}
$$

$$
 F_{B} = \frac{b}{L^2} (\Delta v \cdot \Delta p) \Delta p
$$

Written out with scalars:

 $$
 F_{Bx} = b \cdot  \frac{(v_{Ax} - v_{Bx})(x_{A} - x_{B}) + (v_{Ay} - v_{By})(y_{A} - y_{B})}{(x_A - x_B)^2 + (y_A - y_B)^2} \cdot (x_A - x_B)
 $$

$$
 F_{By} = b \cdot  \frac{(v_{Ax} - v_{Bx})(x_{A} - x_{B}) + (v_{Ay} - v_{By})(y_{A} - y_{B})}{(x_A - x_B)^2 + (y_A -y_B)^2} \cdot (y_A - y_B)
$$

Further explanation below if interested:

I derived this by assuming $|| F ||_2 = b \cdot \frac{d}{dt} ||\Delta p||_2$ , i.e. that the force is proportional to the change in length of the damper (the distance between the points). 
The direction of the force was derived by assuming that it will always point in the same or opposite direction of the damper, i.e the direction of $\Delta p$.


The main reason i think the current implementation is wrong is that it can result in the damper force pointing in the same direction as the velocity of point A. An easy example to show this:

$$
    x_A = y_A = y_B = 0, \\; \\; x_B = \pm 1
$$

$$
    v_{Ax} = v_{Ay} = v_{By} = 0, \\; \\; v_{Bx} = 1
$$

First with $x_B = 1$:

$$
 F_{Bx} = - b \cdot (v_{Ax} - v_{Bx}) \cdot \frac{x_A-x_B}{\textit{length}} = - b \cdot (0 - 1) \cdot \frac{0 - 1}{1} = - b
$$

Second with $x_B = -1$:

$$
 F_{Bx} = - b \cdot (v_{Ax} - v_{Bx}) \cdot \frac{x_A-x_B}{\textit{length}} = - b \cdot (0 + 1) \cdot \frac{0 - 1}{1} = b
$$

Since $b \geq 0$ one can see that in the second case $v_{Bx}$ has the same sign as $F_{Bx}$. This then results a unstable feedback loop where the force will increase the velocity that will again increase the force. I think that it is these kind of cases that causes the undesired behaviors. 

Let me know if you disagree or if you want more explanation.

**Comment by SSkjong** [comment]
If you want, you can change the implementation and send me the file. Then I can compile a version for you to test :)
(stian.skjong@sintef.no)

**Comment by KristofferSkare** [comment]
Thanks for compiling the FMUs!

I ran a simulation now with the same parameters as stated in the first comment in the issue and the result looks much more realistic.

![image](https://github.com/open-simulation-platform/demo-cases/assets/52509111/db58beaf-b59c-441e-958e-148b2960227a)

Here the signals seem to result in damped sinusoids after some transient as expected.  So I think it is correctly implemented now. My code in the Damper FMU might have room for improvement, but I think that it now is implementing correct theoretical equations. 

Let me know if you want me to do something more :)

**Comment by SSkjong** [comment]
Perfect!
If you want you can make a PR with the new models. I cross-compiled them, so there should be binaries for both windows and linux.

**Comment by KristofferSkare** [comment]
I can make a PR, but I do not seem to have access to push to a branch. 

I could make a fork or I could get more access to this repo. What do you prefer?

**Comment by SSkjong** [comment]
Ah, no problem. I can do it :)
